[package]
name = "sandbox"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
data = { path = "../data" }
